/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'narration' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'narration' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };